use perltidy -ce -l=0 -et=4

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,291 +1,291 @@
 aliases = {
-    J        = "join";
-    WJOIN    = "join -window";
-    WQUERY   = "query -window";
-    LEAVE    = "part";
-    BYE      = "quit";
-    EXIT     = "quit";
-    SIGNOFF  = "quit";
-    DESCRIBE = "action";
-    DATE     = "time";
-    HOST     = "userhost";
-    LAST     = "lastlog";
-    SAY      = "msg *";
-    WI       = "whois";
-    WII      = "whois $0 $0";
-    WW       = "whowas";
-    W        = "who";
-    N        = "names";
-    M        = "msg";
-    T        = "topic";
-    C        = "clear";
-    CL       = "clear";
-    K        = "kick";
-    KB       = "kickban";
-    KN       = "knockout";
-    BANS     = "ban";
-    B        = "ban";
-    MUB      = "unban *";
-    UB       = "unban";
-    IG       = "ignore";
-    UNIG     = "unignore";
-    SB       = "scrollback";
-    UMODE    = "mode $N";
-    WC       = "window close";
-    WN       = "window new hide";
-    SV       = "say Irssi $J ($V) - http://irssi.org/";
-    GOTO     = "sb goto";
-    CHAT     = "dcc chat";
-    RUN      = "SCRIPT LOAD";
-    CALC     = "exec - if command -v bc >/dev/null 2>&1\\; then printf '%s=' '$*'\\; echo '$*' | bc -l\\; else echo bc was not found\\; fi";
-    SBAR       = "STATUSBAR";
-    INVITELIST = "mode $C +I";
-    Q          = "QUERY";
-    "MANUAL-WINDOWS" = "set use_status_window off;set autocreate_windows off;set autocreate_query_level none;set autoclose_windows off;set reuse_unused_windows on;save";
-    EXEMPTLIST = "mode $C +e";
-    ATAG       = "WINDOW SERVER";
-    UNSET      = "set -clear";
-    RESET      = "set -default";
+	J          = "join";
+	WJOIN      = "join -window";
+	WQUERY     = "query -window";
+	LEAVE      = "part";
+	BYE        = "quit";
+	EXIT       = "quit";
+	SIGNOFF    = "quit";
+	DESCRIBE   = "action";
+	DATE       = "time";
+	HOST       = "userhost";
+	LAST       = "lastlog";
+	SAY        = "msg *";
+	WI         = "whois";
+	WII        = "whois $0 $0";
+	WW         = "whowas";
+	W          = "who";
+	N          = "names";
+	M          = "msg";
+	T          = "topic";
+	C          = "clear";
+	CL         = "clear";
+	K          = "kick";
+	KB         = "kickban";
+	KN         = "knockout";
+	BANS       = "ban";
+	B          = "ban";
+	MUB        = "unban *";
+	UB         = "unban";
+	IG         = "ignore";
+	UNIG       = "unignore";
+	SB         = "scrollback";
+	UMODE      = "mode $N";
+	WC         = "window close";
+	WN         = "window new hide";
+	SV         = "say Irssi $J ($V) - http://irssi.org/";
+	GOTO       = "sb goto";
+	CHAT       = "dcc chat";
+	RUN        = "SCRIPT LOAD";
+	CALC       = "exec - if command -v bc >/dev/null 2>&1\\; then printf '%s=' '$*'\\; echo '$*' | bc -l\\; else echo bc was not found\\; fi";
+	SBAR       = "STATUSBAR";
+	INVITELIST = "mode $C +I";
+	Q          = "QUERY";
+	"MANUAL-WINDOWS" = "set use_status_window off;set autocreate_windows off;set autocreate_query_level none;set autoclose_windows off;set reuse_unused_windows on;save";
+	EXEMPTLIST = "mode $C +e";
+	ATAG       = "WINDOW SERVER";
+	UNSET      = "set -clear";
+	RESET      = "set -default";
 };
 
 statusbar = {
 
-    # formats:
-    # when using {templates}, the template is shown only if it's argument isn't
-    # empty unless no argument is given. for example {sb} is printed always,
-    # but {sb $T} is printed only if $T isn't empty.
+	# formats:
+	# when using {templates}, the template is shown only if it's argument isn't
+	# empty unless no argument is given. for example {sb} is printed always,
+	# but {sb $T} is printed only if $T isn't empty.
 
-    items = {
+	items = {
 
-        # start/end text in statusbars
-        barstart = "{sbstart}";
-        barend   = "{sbend}";
+		# start/end text in statusbars
+		barstart = "{sbstart}";
+		barend   = "{sbend}";
 
-        topicbarstart = "{topicsbstart}";
-        topicbarend   = "{topicsbend}";
+		topicbarstart = "{topicsbstart}";
+		topicbarend   = "{topicsbend}";
 
-        # treated "normally", you could change the time/user name to whatever
-        time = "%K {sb %G$Z}%K {sbaway $A} %g$topic%K";
-        user = "{sb {sbnickmode $cumode}{sbmode $usermode}}";
+		# treated "normally", you could change the time/user name to whatever
+		time = "%K {sb %G$Z}%K {sbaway $A} %g$topic%K";
+		user = "{sb {sbnickmode $cumode}{sbmode $usermode}}";
 
-        # treated specially .. window is printed with non-empty windows,
-        # window_empty is printed with empty windows
+		# treated specially .. window is printed with non-empty windows,
+		# window_empty is printed with empty windows
 
-        window = "";
+		window = "";
 
-        #window_empty = "{sb %C{sbservertag $tag}}%n";
-        window_empty = "{sb $winref/{sbservertag $tag}}";
+		#window_empty = "{sb %C{sbservertag $tag}}%n";
+		window_empty = "{sb $winref/{sbservertag $tag}}";
 
-        #prompt = "$winref%K/{prompt $[.15]itemname}";
-        prompt       = "";
-        prompt_empty = "{prompt $winname}";
-        topic        = " $topic";
-        topic_empty  = " Irssi v$J - http://irssi.org/help/";
+		#prompt = "$winref%K/{prompt $[.15]itemname}";
+		prompt       = "";
+		prompt_empty = "{prompt $winname}";
+		topic        = " $topic";
+		topic_empty  = " Irssi v$J - http://irssi.org/help/";
 
-        # all of these treated specially, they're only displayed when needed
-        lag  = "{sb Lag: $0-}";
-        act  = "{sb $0-}";
-        more = "-- %Ymore below%n --";
-    };
+		# all of these treated specially, they're only displayed when needed
+		lag  = "{sb Lag: $0-}";
+		act  = "{sb $0-}";
+		more = "-- %Ymore below%n --";
+	};
 
-    # there's two type of statusbars. root statusbars are either at the top
-    # of the screen or at the bottom of the screen. window statusbars are at
-    # the top/bottom of each split window in screen.
-    default = {
+	# there's two type of statusbars. root statusbars are either at the top
+	# of the screen or at the bottom of the screen. window statusbars are at
+	# the top/bottom of each split window in screen.
+	default = {
 
-        # the "default statusbar" to be displayed at the bottom of the window.
-        # contains all the normal items.
-        window = {
-            disabled = "no";
+		# the "default statusbar" to be displayed at the bottom of the window.
+		# contains all the normal items.
+		window = {
+			disabled = "no";
 
-            # window, root
-            type = "window";
+			# window, root
+			type = "window";
 
-            # top, bottom
-            placement = "top";
+			# top, bottom
+			placement = "top";
 
-            # number
-            position = "1";
+			# number
+			position = "1";
 
-            # active, inactive, always
-            visible = "active";
+			# active, inactive, always
+			visible = "active";
 
-            # list of items in statusbar in the display order
-            items = {
-                barstart = { priority = "100"; };
-                time = {};
-                user         = {};
-                window       = {};
-                window_empty = {};
-                lag          = { priority = "-1"; };
-                more         = {
-                    priority  = "-1";
-                    alignment = "right";
-                };
-                barend = {
-                    priority  = "100";
-                    alignment = "right";
-                };
-            };
-        };
+			# list of items in statusbar in the display order
+			items = {
+				barstart = { priority = "100"; };
+				time = {};
+				user         = {};
+				window       = {};
+				window_empty = {};
+				lag          = { priority = "-1"; };
+				more         = {
+					priority  = "-1";
+					alignment = "right";
+				};
+				barend = {
+					priority  = "100";
+					alignment = "right";
+				};
+			};
+		};
 
-        # statusbar to use in inactive split windows
-        window_inact = {
-            type      = "window";
-            placement = "bottom";
-            position  = "1";
-            visible   = "inactive";
-            items     = {
-                barstart = { priority = "100"; };
-                window = {};
-                window_empty = {};
-                more         = {
-                    priority  = "-1";
-                    alignment = "right";
-                };
-                barend = {
-                    priority  = "100";
-                    alignment = "right";
-                };
-            };
-            disabled = "yes";
-        };
+		# statusbar to use in inactive split windows
+		window_inact = {
+			type      = "window";
+			placement = "bottom";
+			position  = "1";
+			visible   = "inactive";
+			items     = {
+				barstart = { priority = "100"; };
+				window = {};
+				window_empty = {};
+				more         = {
+					priority  = "-1";
+					alignment = "right";
+				};
+				barend = {
+					priority  = "100";
+					alignment = "right";
+				};
+			};
+			disabled = "yes";
+		};
 
-        # we treat input line as yet another statusbar :) It's possible to
-        # add other items before or after the input line item.
-        prompt = {
-            type      = "root";
-            placement = "bottom";
+		# we treat input line as yet another statusbar :) It's possible to
+		# add other items before or after the input line item.
+		prompt = {
+			type      = "root";
+			placement = "bottom";
 
-            # we want to be at the bottom always
-            position = "1";
-            visible  = "active";
-            items    = { input = {}; };
-        };
+			# we want to be at the bottom always
+			position = "1";
+			visible  = "active";
+			items    = { input = {}; };
+		};
 
-        # topicbar
-        topic = {
-            type      = "root";
-            placement = "top";
-            position  = "2";
-            visible   = "always";
-            items     = {
-                topicbarstart = { priority = "100"; };
-                topic         = {};
-                topic_empty   = {};
-                topicbarend   = {
-                    priority  = "100";
-                    alignment = "right";
-                };
-            };
-            disabled = "yes";
-        };
-        window_add = {
-            items    = {};
-            disabled = "yes";
-        };
-        add = { disabled = "yes"; };
-        delete = { disabled = "yes"; };
-        prompt_empty = {
-            position = "0";
-            disabled = "yes";
-        };
+		# topicbar
+		topic = {
+			type      = "root";
+			placement = "top";
+			position  = "2";
+			visible   = "always";
+			items     = {
+				topicbarstart = { priority = "100"; };
+				topic         = {};
+				topic_empty   = {};
+				topicbarend   = {
+					priority  = "100";
+					alignment = "right";
+				};
+			};
+			disabled = "yes";
+		};
+		window_add = {
+			items    = {};
+			disabled = "yes";
+		};
+		add = { disabled = "yes"; };
+		delete = { disabled = "yes"; };
+		prompt_empty = {
+			position = "0";
+			disabled = "yes";
+		};
 
-        #   rollestatus = { items = {  = { }; }; disabled = "yes"; };
-        #   status = { items = { }; disabled = "yes"; };
-        #   rollstatus = { disabled = "yes"; };
-        asd = {
-            position  = "0";
-            placement = "bottom";
-            items     = {};
-            disabled  = "yes";
-        };
-        topic_empty = { disabled = "yes"; };
-        remove = {
-            items    = {};
-            disabled = "yes";
-        };
-        channels = {
-            items = { chanact = {}; };
-            disabled = "yes";
-        };
-        statusbar = {
+		#   rollestatus = { items = {  = { }; }; disabled = "yes"; };
+		#   status = { items = { }; disabled = "yes"; };
+		#   rollstatus = { disabled = "yes"; };
+		asd = {
+			position  = "0";
+			placement = "bottom";
+			items     = {};
+			disabled  = "yes";
+		};
+		topic_empty = { disabled = "yes"; };
+		remove = {
+			items    = {};
+			disabled = "yes";
+		};
+		channels = {
+			items = { chanact = {}; };
+			disabled = "yes";
+		};
+		statusbar = {
 
-            #rollen statusbar:
+			#rollen statusbar:
 
-            items = {
+			items = {
 
-                #           barstart = "--------------";
-                erotin = {
-                    items = { barstart = "asdasd--------------"; };
-                    priority  = "100";
-                    alignment = "left";
-                    disabled  = "no";
-                    placement = "bottom";
-                    position  = "0";
-                };
-            };
-        };
-        "-before" = { disabled = "yes"; };
-        aw1_0 = {
-            position = "0";
-            disabled = "yes";
-        };
-        empty = {
-            placement = "bottom";
-            position  = "0";
-            disabled  = "yes";
-        };
-        awl_0 = {
-            items = {
-                barstart = { priority = "100"; };
-                awl_0     = {};
-                barend    = {
-                    priority  = "100";
-                    alignment = "right";
-                };
-            };
-        };
-    };
+				#           barstart = "--------------";
+				erotin = {
+					items = { barstart = "asdasd--------------"; };
+					priority  = "100";
+					alignment = "left";
+					disabled  = "no";
+					placement = "bottom";
+					position  = "0";
+				};
+			};
+		};
+		"-before" = { disabled = "yes"; };
+		aw1_0 = {
+			position = "0";
+			disabled = "yes";
+		};
+		empty = {
+			placement = "bottom";
+			position  = "0";
+			disabled  = "yes";
+		};
+		awl_0 = {
+			items = {
+				barstart = { priority = "100"; };
+				awl_0    = {};
+				barend   = {
+					priority  = "100";
+					alignment = "right";
+				};
+			};
+		};
+	};
 };
 settings = {
-    core = {
-        real_name = "username";
-        user_name = "username";
-        nick      = "username";
-        quit_message = "bye!";
-        resolve_prefer_ipv6 = "yes";
-    };
-    "fe-text" = {
-        actlist_sort      = "refnum";
-        scroll_page_count = "5";
-        scrollback_time = "7days";
-    };
-    "fe-common/core" = {
-        theme          = "weed";
-        autolog        = "yes";
-        autolog_path   = "~/irssi-logs/$tag/$0/%Y/%m-%d.log";
-        window_history = "yes";
-    };
-    "perl/core/scripts" = {
-        awl_viewer         = "no";
-        awl_all_disable    = "no";
-        awl_block          = "30";
-        awl_height_adjust  = "1";
-        awl_hide_data      = "0";
-        awl_maxlines       = "1";
-        awl_placement      = "bottom";
-        awl_position       = "0";
-        awl_prefer_name    = "yes";
-        awl_sbar_maxlength = "yes";
-        awl_sort           = "refnum";
-        awl_shared_sbar    = "OFF";
-        neat_colors        = "X30rRX61X6CX3CyX1DcCBX3HX2AbMX3AX42X6M";
-        trackbar_style     = "%K";
-        trackbar_string    = "-";
-        smartfilter_delay  = "1200";
-    };
-    "irc/core" = { skip_motd = "yes"; };
+	core = {
+		real_name           = "username";
+		user_name           = "username";
+		nick                = "username";
+		quit_message        = "bye!";
+		resolve_prefer_ipv6 = "yes";
+	};
+	"fe-text" = {
+		actlist_sort      = "refnum";
+		scroll_page_count = "5";
+		scrollback_time   = "7days";
+	};
+	"fe-common/core" = {
+		theme          = "weed";
+		autolog        = "yes";
+		autolog_path   = "~/irssi-logs/$tag/$0/%Y/%m-%d.log";
+		window_history = "yes";
+	};
+	"perl/core/scripts" = {
+		awl_viewer         = "no";
+		awl_all_disable    = "no";
+		awl_block          = "30";
+		awl_height_adjust  = "1";
+		awl_hide_data      = "0";
+		awl_maxlines       = "1";
+		awl_placement      = "bottom";
+		awl_position       = "0";
+		awl_prefer_name    = "yes";
+		awl_sbar_maxlength = "yes";
+		awl_sort           = "refnum";
+		awl_shared_sbar    = "OFF";
+		neat_colors        = "X30rRX61X6CX3CyX1DcCBX3HX2AbMX3AX42X6M";
+		trackbar_style     = "%K";
+		trackbar_string    = "-";
+		smartfilter_delay  = "1200";
+	};
+	"irc/core" = { skip_motd = "yes"; };
 };
 
 logs = {};
